name: CD Pipeline

on:
    push:
        branches: [ main, stage, devel ]

jobs:
    deploy:
        runs-on: ubuntu-latest
    
        env:
            BUCKET_NAME: ${{ (github.ref == 'refs/heads/main' && 'rdicidr-app-prod') || (github.ref == 'refs/heads/stage' && 'rdicidr-app-stage') || (github.ref == 'refs/heads/devel' && 'rdicidr-app-devel') }}
            DISTRIBUTION_ID: ${{ (github.ref == 'refs/heads/main' && secrets.PROD_DISTRIBUTION_ID) || (github.ref == 'refs/heads/stage' && secrets.STAGE_DISTRIBUTION_ID) || (github.ref == 'refs/heads/devel' && secrets.DEVEL_DISTRIBUTION_ID) }}
    
        permissions:
            id-token: write
            contents: read
    
        steps:
        - name: Check out code
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '15'

        - name: Install dependencies
          run: npm ci
          
        - name: Build project
          run: npm run build
        - name: Configure AWS Credential
          uses: aws-actions/configure-aws-credentials@v5.1.0
          with:
              role-to-asume: ${{secrets.AWS_OIDC_ROLE_ARN}}
              aws-region: us-east-2
        - name: Deploy to S3
          run: aws s3 sync ./build s3://${{env.BUCKET_NAME}} --delete
        - name: Invalidate Cache
          run: |
            aws cloudfront create-invalidation \
                --distribution-id ${{env.DISTRIBUTION_ID}} \
                --paths "/*"

    
